version: '3.8'

services:
  create-htpasswd:
    image: registry:2
    container_name: stream-htpasswd
    entrypoint: sh
    command: -c "apk add --no-cache apache2-utils && htpasswd -Bbn admin 123456 > /var/lib/registry/nginx.htpasswd"
    volumes:
      - ./auth:/var/lib/registry

  app:
# -- manual container
    build:
     context: ./
     dockerfile: Dockerfile
# -- ogiginal image
#    image: php:fpm-alpine3.20
#    command: sh -c "apk add --no-cache unzip ffmpeg && nginx -g 'daemon off;'"
    container_name: stream-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ../src:/var/www  
    command: sh -c "mkdir -p /var/www/public/uploads /var/www/public/media && chmod -R 777 /var/www/public/uploads /var/www/public/media && php-fpm"

  nginx:
    image: nginx:1.19-alpine
    container_name: stream-nginx
    restart: always
    ports:
      - 8000:80
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
      - ./auth:/etc/nginx/auth
